executor: cluster-generic
cluster-generic-submit-cmd:
  sbatch
    --account=hpc_build  
    --partition=standard
    --output={resources.log_dir}/{rule}.%A.out
    --error={resources.log_dir}/{rule}.%A.err
    --job-name={rule}
    --cpus-per-task={threads}
    --nodes=1
    --time={resources.time_limit}
    --mem={resources.memory_limit}G
    --parsable
cluster-generic-status-cmd: ~/DAC/Bergland/DESTv3/snpCalling_dev_FB/slurm/slurm_job_status.sh
default-resources: 
  - memory_limit=4
  - time_limit=60
scheduler: greedy
jobs: 100
keep-going: True
retries: 3
rerun-incomplete: True
show-failed-logs: True
latency-wait: 20
#printshellcmds: True


 

