FROM ubuntu:20.04

# version pinning
ARG CUTADAPT_VERSION=2.3 \
    GATK_VERSION=3.8-1-0 \
    PICARD_VERSION=2.20.2
ENV DEBIAN_FRONTEND=noninteractive

# apt:
# - tools
# - libraries
# - languages
#   - Java 21
#   - Python 3.8.2
#   - R 3.6.3
# - applications
#   - bbmap 38.79
#   - bwa 0.7.17
#   - fastqc 0.11.9
#   - htslib 1.10.2
#   - samtools 1.10 
# - snape-pooled dependency
    
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates git wget unzip \
        libbz2-dev liblzma-dev libopenblas-dev zlib1g-dev \
        openjdk-8-jre python3-dev python3-pip r-base \
        bbmap bwa fastqc libhts-dev samtools \
        ocaml-nox \
    && rm -rf /var/lib/apt/lists/*

# Python packages
RUN pip install --no-cache-dir cutadapt==$CUTADAPT_VERSION

# R packages
RUN R -e "install.packages(c('data.table'), repos='https://cran.r-project.org')"

# Applications not available through package managers
# Picard
RUN mkdir -p /opt/picard/${PICARD_VERSION} && \
    cd /opt/picard/${PICARD_VERSION} && \
    wget https://github.com/broadinstitute/picard/releases/download/${PICARD_VERSION}/picard.jar
ENV CLASSPATH="/opt/picard/${PICARD_VERSION}/picard.jar:$CLASSPATH"
ENV PICARD="/opt/picard/${PICARD_VERSION}/picard.jar"

# GATK
WORKDIR /opt
RUN wget -q https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2 && \
    tar -xvf GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2 && \
    mv GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef gatk && \
    rm GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2
ENV CLASSPATH="/opt/gatk/GenomeAnalysisTK.jar:$CLASSPATH"
ENV GATK="/opt/gatk/GenomeAnalysisTK.jar"

# snape-pooled
# deprecated in ocaml:
# - Array.create -> Array.make
# - String.uppercase -> String.uppercase_ascii

RUN git clone https://github.com/DEST-bio/snape-pooled.git && \
    cd snape-pooled && \
    sed -i -e 's/Array.create/Array.make/g' \
           -e 's/String.uppercase/String.uppercase_ascii/g' \
        pooled.ml && \
    make snape-pooled && \
    cd ..

ENV PATH="/opt/snape-pooled:${PATH}"

# DEST-bio

RUN git clone https://github.com/DEST-bio/DESTv3.git && \
    cd DESTv3 && \
    git checkout main && \
    cd ..

ARG CACHE_BUST=06:03:2020:1800

ENV PATH="/opt/DESTv3/mappingPipeline/scripts:${PATH}" \
    LC_ALL=C

#Command to execute on "docker run" of this image
ENTRYPOINT ["/bin/bash", "/opt/DESTv3/mappingPipeline/scripts/fq_to_sync_pipeline.v3.0.0.sh"]

#Default parameters passed to the above function call. Can be overridden by supplying parameters after image name in "docker run"
CMD ["--help"]
