FROM python:3.13.12-slim-trixie

# version pinning
ARG CUTADAPT_VERSION= \
    GATK_VERSION=3.8-1-0

# apt:
# - tools
# - libraries
# - languages
#   - Java 21
#   - R 4.5.0
# - applications
#   - bbmap 39.20
#   - bwa 0.7.18
#   - fastqc 0.12.1
#   - htslib 1.21
#   - picard 3.3.0
#   - samtools 1.21 
# - snape-pooled dependency
    
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates git wget unzip \
        libbz2-dev liblzma-dev libopenblas-dev zlib1g-dev \
        openjdk-21-jre r-base \
        bbmap bwa fastqc libhts-dev picard-tools samtools \
        ocaml-nox \
    && rm -rf /var/lib/apt/lists/*

# Python packages
RUN pip install --no-cache-dir cutadapt

# R packages
RUN R -e "install.packages(c('data.table'), repos='https://cran.r-project.org')"

# Applications not available through package managers
WORKDIR /opt

RUN wget -q https://storage.googleapis.com/gatk-software/package-archive/gatk/GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2 && \
    tar -xvf GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2 && \
    mv GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef gatk && \
    rm GenomeAnalysisTK-${GATK_VERSION}-gf15c1c3ef.tar.bz2
ENV CLASSPATH="/opt/gatk/GenomeAnalysisTK.jar:$CLASSPATH"
ENV GATK="/opt/gatk/GenomeAnalysisTK.jar"

# snape-pooled
# deprecated in ocaml:
# - Array.create -> Array.make
# - String.uppercase -> String.uppercase_ascii

RUN git clone https://github.com/DEST-bio/snape-pooled.git && \
    cd snape-pooled && \
    sed -i -e 's/Array.create/Array.make/g' \
           -e 's/String.uppercase/String.uppercase_ascii/g' \
        pooled.ml && \
    make snape-pooled && \
    cd ..

ENV PATH="/opt/snape-pooled:${PATH}"

# DEST-bio

RUN git clone https://github.com/DEST-bio/DESTv3.git && \
    cd DESTv3 && \
    git checkout main && \
    cd ..

ARG CACHE_BUST=06:03:2020:1800

ENV PATH="/opt/DESTv3/mappingPipeline/scripts:${PATH}" \
    LC_ALL=C

#Command to execute on "docker run" of this image
ENTRYPOINT ["/bin/bash", "/opt/DESTv3/mappingPipeline/scripts/fq_to_sync_pipeline.v3.0.0.sh"]

#Default parameters passed to the above function call. Can be overridden by supplying parameters after image name in "docker run"
CMD ["--help"]
